# Site settings
title: *folio
email: quacht@mit.edu
description: > # this means to ignore newlines until "baseurl:"
  Tina learns how to make (almost) anything!
baseurl:  # the subpath of your site, e.g. /blog/
url:  # the base hostname & protocol for your site
github_username:  quachtina96

# Build settings
markdown: kramdown

highlighter: rouge

# Pagination
paginate: 15
paginate_path: "/blog/page:num/"


collections:
  portfolio:
    output: true
    permalink: /portfolio/:path/
  poetry:
    output: true
    permalink: /poetry/:path/


